#!/usr/bin/env python3
"""Part B, adapted drop foot: re-optimized asymmetric controllers at 50, 25 and 10% strength.

    python analysis/curate_runs.py dropfoot_ta25    # and ta50, ta10, first
    python analysis/part_b_adapted.py

Evaluates results/dropfoot_ta<x>/seed<i>/best.par in scenarios/dropfoot_ta<x>.scone
and the healthy results, and writes:

* results/dropfoot/adapted.csv: one row per run (cost, fall, every metric of
  dropfoot.metrics);
* results/dropfoot/metrics_table.md: mean +/- SD over the seeds that walk,
  with the number of seeds that fell, plus the change from healthy of the
  swing hip and knee flexion (steppage);
* results/dropfoot/curves.csv: mean right-stride curves per condition;
* figures/dropfoot_overlay.png: right ankle, knee and hip angles, toe height,
  tibialis anterior activation and the ankle moment over the gait cycle.
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from dropfoot import ROOT
from dropfoot.evaluation import evaluate_cached, is_walking, summarize
from dropfoot.gait import PERCENT, find_strides, normalize_strides

SEEDS = (1, 2, 3)
LEVELS = (0.5, 0.25, 0.1)
OUT = ROOT / "results" / "dropfoot"
FIGURE = ROOT / "figures" / "dropfoot_overlay.png"

METRICS = [
    ("min_toe_clearance_mm", "Min toe clearance, mid swing (mm)"),
    ("ankle_at_ic_deg", "Ankle at initial contact (deg)"),
    ("peak_swing_df_deg", "Peak swing dorsiflexion (deg)"),
    ("foot_slap_index_dps", "Foot slap index (deg/s)"),
    ("peak_hip_flexion_swing_deg", "Peak hip flexion, swing (deg)"),
    ("peak_knee_flexion_swing_deg", "Peak knee flexion, swing (deg)"),
    ("peak_ankle_power_w", "Peak ankle push-off power (W)"),
    ("step_length_si_pct", "Step length SI (%)"),
    ("stance_time_si_pct", "Stance time SI (%)"),
    ("speed_mps", "Speed (m/s)"),
    ("cost_of_transport", "Cost of transport (J/(kg m))"),
    ("stride_time_s", "Stride time (s)"),
    ("stride_length_m", "Stride length (m)"),
]
DECIMALS = {"foot_slap_index_dps": 0, "peak_ankle_power_w": 0, "speed_mps": 2, "cost_of_transport": 2,
            "stride_time_s": 2, "stride_length_m": 2}
CURVES = {
    "ankle_angle": ("ankle_angle_r", np.degrees(1.0), "Ankle angle (deg), + dorsiflexion"),
    "knee_flexion": ("knee_angle_r", -np.degrees(1.0), "Knee flexion (deg)"),
    "hip_flexion": ("hip_flexion_r", np.degrees(1.0), "Hip flexion (deg)"),
    "toe_height": ("toes_r.pos_y", 1000.0, "Toe height (mm)"),
    "tib_ant_activation": ("tib_ant_r.activation", 1.0, "Tibialis anterior activation"),
    "ankle_moment": ("ankle_angle_r.moment", 1.0, "Ankle muscle moment (N m)"),
}


def label(cond: str) -> str:
    return "Healthy" if cond == "healthy" else f"Drop foot, TA {cond[11:]}%, adapted"


def runs():
    for s in SEEDS:
        yield "healthy", s, ROOT / "scenarios/healthy.scone", ROOT / f"results/healthy/seed{s}/best.par", f"healthy_s{s}"
    for f in LEVELS:
        tag = f"ta{round(100 * f):d}"
        for s in SEEDS:
            par = ROOT / f"results/dropfoot_{tag}/seed{s}/best.par"
            if par.exists():
                yield f"dropfoot_{tag}", s, ROOT / f"scenarios/dropfoot_{tag}.scone", par, f"adapted_{tag}_s{s}"


def main() -> None:
    rows, curves = [], {}
    for cond, seed, scen, par, name in runs():
        sto, report = evaluate_cached(scen, par, name)
        row = summarize(sto, report)
        row.update({"condition": cond, "seed": seed, "walks": is_walking(row)})
        rows.append(row)
        if row["walks"]:
            st = find_strides(sto, "r", skip_first=2)
            for key, (chan, scale, _) in CURVES.items():
                curves.setdefault(cond, {}).setdefault(key, []).append(normalize_strides(sto, chan, st, scale=scale).mean(0))
            curves[cond].setdefault("stance", []).append(100 * np.mean([x.stance_fraction for x in st]))
    df = pd.DataFrame(rows)
    first = ["condition", "seed", "walks", "cost", "duration_s", "n_strides"]
    df = df[first + [c for c in df.columns if c not in first]]
    df.to_csv(OUT / "adapted.csv", index=False, float_format="%.6g")

    conds = list(dict.fromkeys(df.condition))
    healthy = df[(df.condition == "healthy") & df.walks]
    lines = [
        "# Drop-foot metrics, right (affected) side",
        "",
        "Mean +/- SD over the seeds that walk 10 s; strides after the two start-up strides. "
        "Steppage is the change of the swing hip and knee flexion peaks from the healthy mean. "
        "Generated by `analysis/part_b_adapted.py`.",
        "",
        "| metric | " + " | ".join(label(c) for c in conds) + " |",
        "|---|" + "---|" * len(conds),
        "| seeds walking / run | " + " | ".join(f"{int(df[df.condition == c].walks.sum())} / {int((df.condition == c).sum())}" for c in conds) + " |",
    ]
    def cell(v: pd.Series, decimals: int, sign: str = "") -> str:
        if not len(v):
            return "n/a"
        mean = f"{round(v.mean(), decimals) + 0.0:{sign}.{decimals}f}"
        return f"{mean} +/- {v.std(ddof=1):.{decimals}f}" if len(v) > 1 else mean

    for key, name in METRICS:
        cells = [cell(df[(df.condition == c) & df.walks][key].dropna(), DECIMALS.get(key, 1)) for c in conds]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    for key, name in (("peak_hip_flexion_swing_deg", "Steppage, hip (deg)"), ("peak_knee_flexion_swing_deg", "Steppage, knee (deg)")):
        ref = healthy[key].mean()
        cells = [cell((df[(df.condition == c) & df.walks][key].dropna() - ref).round(9), 1, "+") for c in conds]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    (OUT / "metrics_table.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))

    out = pd.DataFrame({"percent": PERCENT})
    for c, cv in curves.items():
        for key in CURVES:
            stack = np.vstack(cv[key])
            out[f"{c}.{key}_mean"] = stack.mean(0)
            out[f"{c}.{key}_sd"] = stack.std(0, ddof=1) if len(stack) > 1 else 0.0
    out.to_csv(OUT / "curves.csv", index=False, float_format="%.5g")

    colors = {"healthy": "k", "dropfoot_ta50": "tab:blue", "dropfoot_ta25": "tab:orange", "dropfoot_ta10": "tab:red"}
    fig, axes = plt.subplots(3, 2, figsize=(9, 8.5), sharex=True)
    for ax, (key, (_, _, title)) in zip(axes.T.ravel(), CURVES.items()):
        for c, cv in curves.items():
            stack = np.vstack(cv[key])
            m = stack.mean(0)
            ax.plot(PERCENT, m, color=colors.get(c, "0.5"), lw=1.8, label=f"{label(c)} (n = {len(stack)})")
            if len(stack) > 1:
                ax.fill_between(PERCENT, stack.min(0), stack.max(0), color=colors.get(c, "0.5"), alpha=0.15, lw=0)
            ax.axvline(np.mean(cv["stance"]), color=colors.get(c, "0.5"), ls="--", lw=0.7)
        ax.set_title(title, fontsize=9)
        ax.tick_params(labelsize=8)
    for ax in axes[-1]:
        ax.set_xlabel("Gait cycle (%), right heel strike to heel strike")
        ax.set_xlim(0, 100)
    axes[0, 0].legend(fontsize=7)
    fig.suptitle("Right leg, mean over seeds (band: range over seeds); dashed lines are toe-off", fontsize=10)
    fig.tight_layout()
    fig.savefig(FIGURE, dpi=150)


if __name__ == "__main__":
    main()
