-- Generated by dropfoot.scenarios.lua_bundle from scenarios/lua/device.lua and its modules (gyro, detector, actuator, fsm).
-- Do not edit; run python scripts/bundle_lua.py after changing a module.

package.preload["gyro"] = function( ... )
-- Simulated shank gyroscope (Part D1). Units: deg/s and s.
-- Sign: positive when the shank rotates forward (distal end forward), the
-- sign of tibia_r:ang_vel().z in Human0914 (docs/conventions.md).
--
-- Model, applied to the true sagittal angular velocity w(t):
--   * sampling at rate_hz: sample k is taken at t_k = k / rate_hz, at the
--     first control step with t >= t_k;
--   * y_k = w(t_k) + bias + noise * n_k, with n_k standard normal;
--   * transport delay: y_k becomes available at t_k + delay and is held
--     (zero-order hold) until y_{k+1} becomes available.
-- The normal deviates come from a Park-Miller generator (x <- 16807 x mod
-- 2^31 - 1, exact in double precision) and the Box-Muller transform, so the
-- Python twin dropfoot.sensor.Gyro produces the same sequence from the same seed.

local Gyro = {}
Gyro.__index = Gyro

local MODULUS = 2147483647
local MULTIPLIER = 16807
local EPS = 1e-9

function Gyro.new( rate_hz, noise_dps, bias_dps, delay_s, seed )
	local g = setmetatable( {}, Gyro )
	g.period = 1.0 / rate_hz
	g.noise = noise_dps
	g.bias = bias_dps
	g.delay = delay_s
	g.state = math.floor( seed ) % MODULUS
	if g.state == 0 then g.state = 1 end
	g.k = -1 -- index of the last sample taken
	g.queue = {} -- samples taken but not yet available
	g.head = 1
	g.tail = 0
	g.output = 0.0 -- measured value, held
	g.output_k = -1 -- index of the sample in the output (-1: none yet)
	g.sample_true = 0.0 -- true value at the last sample taken
	return g
end

function Gyro:uniform()
	self.state = ( MULTIPLIER * self.state ) % MODULUS
	return self.state / MODULUS
end

function Gyro:normal()
	local u1 = self:uniform()
	local u2 = self:uniform()
	return math.sqrt( -2.0 * math.log( u1 ) ) * math.cos( 2.0 * math.pi * u2 )
end

-- Advance to time t with the current true value w (deg/s).
-- Returns true when a new measured sample became available at this step.
function Gyro:update( t, w )
	while ( self.k + 1 ) * self.period <= t + EPS do
		self.k = self.k + 1
		self.sample_true = w
		local y = w + self.bias + self.noise * self:normal()
		self.tail = self.tail + 1
		self.queue[ self.tail ] = { available = self.k * self.period + self.delay, value = y, k = self.k }
	end
	local fresh = false
	while self.head <= self.tail and self.queue[ self.head ].available <= t + EPS do
		local s = self.queue[ self.head ]
		self.queue[ self.head ] = nil
		self.head = self.head + 1
		self.output = s.value
		self.output_k = s.k
		fresh = true
	end
	return fresh
end

return Gyro
end

package.preload["detector"] = function( ... )
-- Causal gait-event detector on the measured shank gyroscope (Part D2).
-- Units: deg/s and s. Sign: positive when the shank rotates forward.
-- Python twin: dropfoot.detector.Detector (same states, same arithmetic).
--
-- It runs once per new gyroscope sample (time t = when the sample became
-- available) and uses only that sample and earlier ones. Features of the
-- shank pattern in one stride (docs/conventions.md):
--   swing     the signal rises above swing_dps (mid-swing peak, positive);
--   terminal  after that peak it crosses zero going down;
--   HS        heel strike: with hs_feature = "min", the first negative
--             minimum after the zero crossing, confirmed when the signal has
--             risen hs_rise_dps above it and the minimum is below -hs_depth_dps;
--             with hs_feature = "zero", the zero crossing itself;
--   TO        toe-off: after a lockout of lockout_frac stride times from HS,
--             the negative minimum below -to_depth_dps, confirmed when the
--             signal has risen to_rise_dps above it.
-- An event's time estimate is the time of the sample at the extremum (or
-- the interpolated zero crossing); its detection time is the time at which
-- it was confirmed. Both lag the true event by at least the sensor delay.
-- Gait phase: (t - last HS estimate) / mean of the last 3 stride times,
-- capped at 1; -1 before the first HS.

local Detector = {}
Detector.__index = Detector

local SEARCH, SWING, TERMINAL, STANCE, PRESWING = 0, 1, 2, 3, 4

function Detector.new( cfg )
	local d = setmetatable( {}, Detector )
	d.swing_dps = cfg.swing_dps or 100.0
	d.hs_feature = cfg.hs_feature or "min"
	d.hs_depth_dps = cfg.hs_depth_dps or 50.0
	d.hs_rise_dps = cfg.hs_rise_dps or 20.0
	d.to_depth_dps = cfg.to_depth_dps or 100.0
	d.to_rise_dps = cfg.to_rise_dps or 20.0
	d.lockout_frac = cfg.lockout_frac or 0.35
	d.terminal_timeout = cfg.terminal_timeout or 0.3
	d.stride0 = cfg.stride0 or 1.1
	d.state = SEARCH
	d.t_prev = nil
	d.y_prev = nil
	d.t_enter = 0.0 -- time the current state was entered
	d.ext_y = 0.0 -- running extremum and its time
	d.ext_t = 0.0
	d.hs_time = -1.0
	d.hs_detect = -1.0
	d.to_time = -1.0
	d.to_detect = -1.0
	d.n_hs = 0
	d.n_to = 0
	d.strides = { d.stride0, d.stride0, d.stride0 }
	return d
end

function Detector:mean_stride()
	return ( self.strides[ 1 ] + self.strides[ 2 ] + self.strides[ 3 ] ) / 3.0
end

function Detector:heel_strike( t_event, t )
	if self.n_hs > 0 then
		local T = t_event - self.hs_time
		if T >= 0.6 and T <= 2.0 then
			self.strides[ 1 ] = self.strides[ 2 ]
			self.strides[ 2 ] = self.strides[ 3 ]
			self.strides[ 3 ] = T
		end
	end
	self.hs_time = t_event
	self.hs_detect = t
	self.n_hs = self.n_hs + 1
	self.state = STANCE
	self.t_enter = t
end

-- Feed one sample y that became available at time t. Returns the event
-- detected at this sample: 0 none, 1 heel strike, 2 toe-off.
function Detector:update( t, y )
	local event = 0
	local s = self.state
	if s == SEARCH then
		if y > self.swing_dps then
			self.state = SWING
			self.t_enter = t
		end
	elseif s == SWING then
		if y < 0.0 then
			local tz = t
			if self.y_prev ~= nil and self.y_prev > y then
				tz = self.t_prev + ( t - self.t_prev ) * self.y_prev / ( self.y_prev - y )
			end
			if self.hs_feature == "zero" then
				self:heel_strike( tz, t )
				event = 1
			else
				self.state = TERMINAL
				self.t_enter = t
				self.ext_y = y
				self.ext_t = t
			end
		end
	elseif s == TERMINAL then
		if y < self.ext_y then
			self.ext_y = y
			self.ext_t = t
		end
		if self.ext_y < -self.hs_depth_dps and y > self.ext_y + self.hs_rise_dps then
			self:heel_strike( self.ext_t, t )
			event = 1
		elseif t - self.t_enter > self.terminal_timeout then
			self.state = SEARCH -- lost: wait for the next swing
			self.t_enter = t
		end
	elseif s == STANCE then
		if t - self.hs_time > self.lockout_frac * self:mean_stride() then
			self.state = PRESWING
			self.t_enter = t
			self.ext_y = y
			self.ext_t = t
		end
	elseif s == PRESWING then
		if y < self.ext_y then
			self.ext_y = y
			self.ext_t = t
		end
		if self.ext_y < -self.to_depth_dps and y > self.ext_y + self.to_rise_dps then
			self.to_time = self.ext_t
			self.to_detect = t
			self.n_to = self.n_to + 1
			self.state = SEARCH
			self.t_enter = t
			event = 2
		elseif t - self.hs_time > 2.0 then
			self.state = SEARCH -- no toe-off within 2 s of heel strike
			self.t_enter = t
		end
	end
	self.t_prev = t
	self.y_prev = y
	return event
end

function Detector:phase( t )
	if self.n_hs == 0 then return -1.0 end
	local p = ( t - self.hs_time ) / self:mean_stride()
	if p > 1.0 then p = 1.0 end
	return p
end

return Detector
end

package.preload["actuator"] = function( ... )
-- Closed-loop torque response of the exoskeleton actuator (from Part E):
-- a pure delay followed by a first-order lag, and a symmetric torque limit.
-- Units: N m and s. Python twin: dropfoot.device.ActuatorLag.
--
--   tau_cmd(t)  ->  clip to +-limit  ->  delay  ->  1 / (time_constant s + 1)  ->  tau(t)
--
-- Discretized per control step dt with the exact first-order response to the
-- delayed command held over the step that just ended (zero-order hold):
--   tau <- tau + (u_held - tau) * (1 - exp(-dt / time_constant)),
-- then the delayed command due at t becomes u_held for the next step.
-- With time_constant = 0 the torque is the delayed command itself.

local Actuator = {}
Actuator.__index = Actuator

local EPS = 1e-9

function Actuator.new( delay_s, time_constant_s, limit_nm )
	local a = setmetatable( {}, Actuator )
	a.delay = delay_s
	a.time_constant = time_constant_s
	a.limit = limit_nm
	a.queue = {}
	a.head = 1
	a.tail = 0
	a.delayed = 0.0
	a.torque = 0.0
	a.t_prev = nil
	return a
end

function Actuator:clip( u )
	if u > self.limit then return self.limit end
	if u < -self.limit then return -self.limit end
	return u
end

-- Advance to time t with command u; returns the delivered torque.
function Actuator:update( t, u )
	if self.time_constant > 0 and self.t_prev ~= nil then
		local dt = t - self.t_prev
		self.torque = self.torque + ( self.delayed - self.torque ) * ( 1.0 - math.exp( -dt / self.time_constant ) )
	end
	self.tail = self.tail + 1
	self.queue[ self.tail ] = { t = t + self.delay, u = self:clip( u ) }
	while self.head <= self.tail and self.queue[ self.head ].t <= t + EPS do
		self.delayed = self.queue[ self.head ].u
		self.queue[ self.head ] = nil
		self.head = self.head + 1
	end
	if self.time_constant <= 0 then
		self.torque = self.delayed
	end
	self.t_prev = t
	return self.torque
end

return Actuator
end

package.preload["fsm"] = function( ... )
-- Phase-based finite-state controller of the active AFO (Part F2).
-- Python twin: dropfoot.fsm.PhaseController (same states, same arithmetic).
-- Sign: torque positive when it dorsiflexes; ankle angle positive in
-- dorsiflexion (rad), velocity in rad/s.
--
-- Driven only by the shank-gyroscope detector (its HS and TO events and its
-- phase estimate) and the device's own ankle angle and velocity:
--   OFF          before the first event: no torque;
--   EARLY        from a detected HS until the phase reaches early_frac:
--                viscous braking of plantarflexion, tau = max(0, -b theta_dot);
--   TRANSPARENT  mid and late stance: no torque, so push-off is not resisted;
--   SWING        from a detected TO: PD toward a dorsiflexed target,
--                tau = max(0, kp (target - theta) - kd theta_dot), back to
--                TRANSPARENT after swing_timeout s without a HS (missed event).
-- The device can only lift the foot or brake its fall, as tibialis anterior
-- does, hence the max(0, .). The command then goes through the actuator model.

local FSM = {}
FSM.__index = FSM

FSM.OFF, FSM.EARLY, FSM.TRANSPARENT, FSM.SWING = 0, 1, 2, 3

function FSM.new( cfg )
	local c = setmetatable( {}, FSM )
	c.early_frac = cfg.early_frac or 0.15
	c.b = cfg.brake_nms_per_rad or 1.0
	c.kp = cfg.kp_nm_per_rad or 30.0
	c.kd = cfg.kd_nms_per_rad or 0.6
	c.target = cfg.target_rad or math.rad( 5.0 )
	c.swing_timeout = cfg.swing_timeout_s or 0.8
	c.state = FSM.OFF
	c.t_enter = 0.0
	return c
end

-- event: 0 none, 1 heel strike, 2 toe-off (the detector's return value);
-- phase: the detector's phase estimate at t.
function FSM:update( t, event, phase, theta, theta_dot )
	if event == 1 then
		self.state = FSM.EARLY
		self.t_enter = t
	elseif event == 2 then
		self.state = FSM.SWING
		self.t_enter = t
	end
	if self.state == FSM.EARLY and phase >= self.early_frac then
		self.state = FSM.TRANSPARENT
		self.t_enter = t
	elseif self.state == FSM.SWING and t - self.t_enter > self.swing_timeout then
		self.state = FSM.TRANSPARENT
		self.t_enter = t
	end
	local tau = 0.0
	if self.state == FSM.EARLY then
		tau = -self.b * theta_dot
	elseif self.state == FSM.SWING then
		tau = self.kp * ( self.target - theta ) - self.kd * theta_dot
	end
	if tau < 0.0 then tau = 0.0 end
	return tau
end

return FSM
end

-- Right ankle exoskeleton as a ScriptController (Parts D and F).
-- Sign: the device torque tau is positive when it dorsiflexes the foot.
-- It is applied as an action-reaction pair, +tau on talus_r and -tau on
-- tibia_r, about z. ankle_angle_r is positive in dorsiflexion (rad).
--
-- External moments persist in SCONE (OpenSim 3 adds each call to the body's
-- applied moment), so the script remembers the moment it has applied and adds
-- only the change at each step. Python twin and tests: dropfoot.device.
--
-- Properties (strings, from the ScriptController block):
--   mode          none | constant | passive | active   (default none)
--   constant_nm, on_time, off_time    constant mode: tau between the two times
--   k_nm_per_rad, theta0_rad          passive mode: tau = -k (theta - theta0)
--   early_frac, brake_nms_per_rad, kp_nm_per_rad, kd_nms_per_rad, target_rad,
--   swing_timeout_s                   active mode: the phase-based FSM (fsm.lua)
--   act_delay_s, act_time_constant_s, limit_nm   actuator response (not used in passive mode)
--   and the gyroscope and detector settings of imu.lua, which always run.

local Gyro = require "gyro"
local Detector = require "detector"
local Actuator = require "actuator"
local FSM = require "fsm"
local RAD2DEG = 180.0 / math.pi

local function num( name, default )
	local v = tonumber( scone[ name ] )
	if v == nil then return default end
	return v
end

function init( model, par, side )
	tibia = model:find_body( "tibia_r" )
	talus = model:find_body( "talus_r" )
	ankle = model:find_dof( "ankle_angle_r" )
	mode = scone.mode or "none"

	gyro = Gyro.new( num( "rate_hz", 100 ), num( "noise_dps", 0.5 ), num( "bias_dps", 2.0 ),
		num( "imu_delay_s", 0.015 ), num( "seed", 1 ) )
	detector = Detector.new( {
		swing_dps = num( "swing_dps" ), hs_feature = scone.hs_feature,
		hs_depth_dps = num( "hs_depth_dps" ), hs_rise_dps = num( "hs_rise_dps" ),
		to_depth_dps = num( "to_depth_dps" ), to_rise_dps = num( "to_rise_dps" ),
		lockout_frac = num( "lockout_frac" ), terminal_timeout = num( "terminal_timeout" ),
		stride0 = num( "stride0" ) } )
	actuator = Actuator.new( num( "act_delay_s", 0.0 ), num( "act_time_constant_s", 0.0 ), num( "limit_nm", 1e9 ) )

	constant_nm = num( "constant_nm", 0.0 )
	on_time = num( "on_time", 0.0 )
	off_time = num( "off_time", 1e9 )
	k_spring = num( "k_nm_per_rad", 0.0 )
	theta0 = num( "theta0_rad", 0.0 )
	fsm = FSM.new( {
		early_frac = num( "early_frac" ), brake_nms_per_rad = num( "brake_nms_per_rad" ),
		kp_nm_per_rad = num( "kp_nm_per_rad" ), kd_nms_per_rad = num( "kd_nms_per_rad" ),
		target_rad = num( "target_rad" ), swing_timeout_s = num( "swing_timeout_s" ) } )

	applied = 0.0 -- moment currently applied to talus_r (and its negative to tibia_r)
	command = 0.0
	w_true = 0.0
	theta = 0.0
	theta_dot = 0.0
	power = 0.0
end

function apply( tau )
	local change = tau - applied
	if change ~= 0.0 then
		talus:add_external_moment( 0, 0, change )
		tibia:add_external_moment( 0, 0, -change )
		applied = tau
	end
end

function update( model, t )
	w_true = tibia:ang_vel().z * RAD2DEG
	local event = 0
	if gyro:update( t, w_true ) then
		event = detector:update( t, gyro.output )
	end
	theta = ankle:position()
	theta_dot = ankle:velocity()

	local tau
	if mode == "constant" then
		if t >= on_time and t < off_time then command = constant_nm else command = 0.0 end
		tau = actuator:update( t, command )
	elseif mode == "passive" then
		command = -k_spring * ( theta - theta0 )
		tau = command -- a spring has no actuator lag
	elseif mode == "active" then
		command = fsm:update( t, event, detector:phase( t ), theta, theta_dot )
		tau = actuator:update( t, command )
	else
		command = 0.0
		tau = 0.0
	end
	apply( tau )
	power = applied * theta_dot
	return false
end

function store_data( frame )
	frame:set_value( "imu.true", w_true )
	frame:set_value( "imu.measured", gyro.output )
	frame:set_value( "imu.output_k", gyro.output_k )
	frame:set_value( "det.state", detector.state )
	frame:set_value( "det.n_hs", detector.n_hs )
	frame:set_value( "det.n_to", detector.n_to )
	frame:set_value( "det.hs_time", detector.hs_time )
	frame:set_value( "det.to_time", detector.to_time )
	frame:set_value( "det.phase", detector:phase( frame:time() ) )
	frame:set_value( "dev.state", fsm.state )
	frame:set_value( "dev.command", command )
	frame:set_value( "dev.torque", applied )
	frame:set_value( "dev.power", power )
	frame:set_value( "dev.theta", theta )
end
