-- Generated by dropfoot.scenarios.lua_bundle from scenarios/lua/imu.lua and its modules (gyro, detector).
-- Do not edit; run python scripts/bundle_lua.py after changing a module.

package.preload["gyro"] = function( ... )
-- Simulated shank gyroscope (Part D1). Units: deg/s and s.
-- Sign: positive when the shank rotates forward (distal end forward), the
-- sign of tibia_r:ang_vel().z in Human0914 (docs/conventions.md).
--
-- Model, applied to the true sagittal angular velocity w(t):
--   * sampling at rate_hz: sample k is taken at t_k = k / rate_hz, at the
--     first control step with t >= t_k;
--   * y_k = w(t_k) + bias + noise * n_k, with n_k standard normal;
--   * transport delay: y_k becomes available at t_k + delay and is held
--     (zero-order hold) until y_{k+1} becomes available.
-- The normal deviates come from a Park-Miller generator (x <- 16807 x mod
-- 2^31 - 1, exact in double precision) and the Box-Muller transform, so the
-- Python twin dropfoot.sensor.Gyro produces the same sequence from the same seed.

local Gyro = {}
Gyro.__index = Gyro

local MODULUS = 2147483647
local MULTIPLIER = 16807
local EPS = 1e-9

function Gyro.new( rate_hz, noise_dps, bias_dps, delay_s, seed )
	local g = setmetatable( {}, Gyro )
	g.period = 1.0 / rate_hz
	g.noise = noise_dps
	g.bias = bias_dps
	g.delay = delay_s
	g.state = math.floor( seed ) % MODULUS
	if g.state == 0 then g.state = 1 end
	g.k = -1 -- index of the last sample taken
	g.queue = {} -- samples taken but not yet available
	g.head = 1
	g.tail = 0
	g.output = 0.0 -- measured value, held
	g.output_k = -1 -- index of the sample in the output (-1: none yet)
	g.sample_true = 0.0 -- true value at the last sample taken
	return g
end

function Gyro:uniform()
	self.state = ( MULTIPLIER * self.state ) % MODULUS
	return self.state / MODULUS
end

function Gyro:normal()
	local u1 = self:uniform()
	local u2 = self:uniform()
	return math.sqrt( -2.0 * math.log( u1 ) ) * math.cos( 2.0 * math.pi * u2 )
end

-- Advance to time t with the current true value w (deg/s).
-- Returns true when a new measured sample became available at this step.
function Gyro:update( t, w )
	while ( self.k + 1 ) * self.period <= t + EPS do
		self.k = self.k + 1
		self.sample_true = w
		local y = w + self.bias + self.noise * self:normal()
		self.tail = self.tail + 1
		self.queue[ self.tail ] = { available = self.k * self.period + self.delay, value = y, k = self.k }
	end
	local fresh = false
	while self.head <= self.tail and self.queue[ self.head ].available <= t + EPS do
		local s = self.queue[ self.head ]
		self.queue[ self.head ] = nil
		self.head = self.head + 1
		self.output = s.value
		self.output_k = s.k
		fresh = true
	end
	return fresh
end

return Gyro
end

package.preload["detector"] = function( ... )
-- Causal gait-event detector on the measured shank gyroscope (Part D2).
-- Units: deg/s and s. Sign: positive when the shank rotates forward.
-- Python twin: dropfoot.detector.Detector (same states, same arithmetic).
--
-- It runs once per new gyroscope sample (time t = when the sample became
-- available) and uses only that sample and earlier ones. Features of the
-- shank pattern in one stride (docs/conventions.md):
--   swing     the signal rises above swing_dps (mid-swing peak, positive);
--   terminal  after that peak it crosses zero going down;
--   HS        heel strike: with hs_feature = "min", the first negative
--             minimum after the zero crossing, confirmed when the signal has
--             risen hs_rise_dps above it and the minimum is below -hs_depth_dps;
--             with hs_feature = "zero", the zero crossing itself;
--   TO        toe-off: after a lockout of lockout_frac stride times from HS,
--             the negative minimum below -to_depth_dps, confirmed when the
--             signal has risen to_rise_dps above it.
-- An event's time estimate is the time of the sample at the extremum (or
-- the interpolated zero crossing); its detection time is the time at which
-- it was confirmed. Both lag the true event by at least the sensor delay.
-- Gait phase: (t - last HS estimate) / mean of the last 3 stride times,
-- capped at 1; -1 before the first HS.

local Detector = {}
Detector.__index = Detector

local SEARCH, SWING, TERMINAL, STANCE, PRESWING = 0, 1, 2, 3, 4

function Detector.new( cfg )
	local d = setmetatable( {}, Detector )
	d.swing_dps = cfg.swing_dps or 100.0
	d.hs_feature = cfg.hs_feature or "min"
	d.hs_depth_dps = cfg.hs_depth_dps or 50.0
	d.hs_rise_dps = cfg.hs_rise_dps or 20.0
	d.to_depth_dps = cfg.to_depth_dps or 100.0
	d.to_rise_dps = cfg.to_rise_dps or 20.0
	d.lockout_frac = cfg.lockout_frac or 0.35
	d.terminal_timeout = cfg.terminal_timeout or 0.3
	d.stride0 = cfg.stride0 or 1.1
	d.state = SEARCH
	d.t_prev = nil
	d.y_prev = nil
	d.t_enter = 0.0 -- time the current state was entered
	d.ext_y = 0.0 -- running extremum and its time
	d.ext_t = 0.0
	d.hs_time = -1.0
	d.hs_detect = -1.0
	d.to_time = -1.0
	d.to_detect = -1.0
	d.n_hs = 0
	d.n_to = 0
	d.strides = { d.stride0, d.stride0, d.stride0 }
	return d
end

function Detector:mean_stride()
	return ( self.strides[ 1 ] + self.strides[ 2 ] + self.strides[ 3 ] ) / 3.0
end

function Detector:heel_strike( t_event, t )
	if self.n_hs > 0 then
		local T = t_event - self.hs_time
		if T >= 0.6 and T <= 2.0 then
			self.strides[ 1 ] = self.strides[ 2 ]
			self.strides[ 2 ] = self.strides[ 3 ]
			self.strides[ 3 ] = T
		end
	end
	self.hs_time = t_event
	self.hs_detect = t
	self.n_hs = self.n_hs + 1
	self.state = STANCE
	self.t_enter = t
end

-- Feed one sample y that became available at time t. Returns the event
-- detected at this sample: 0 none, 1 heel strike, 2 toe-off.
function Detector:update( t, y )
	local event = 0
	local s = self.state
	if s == SEARCH then
		if y > self.swing_dps then
			self.state = SWING
			self.t_enter = t
		end
	elseif s == SWING then
		if y < 0.0 then
			local tz = t
			if self.y_prev ~= nil and self.y_prev > y then
				tz = self.t_prev + ( t - self.t_prev ) * self.y_prev / ( self.y_prev - y )
			end
			if self.hs_feature == "zero" then
				self:heel_strike( tz, t )
				event = 1
			else
				self.state = TERMINAL
				self.t_enter = t
				self.ext_y = y
				self.ext_t = t
			end
		end
	elseif s == TERMINAL then
		if y < self.ext_y then
			self.ext_y = y
			self.ext_t = t
		end
		if self.ext_y < -self.hs_depth_dps and y > self.ext_y + self.hs_rise_dps then
			self:heel_strike( self.ext_t, t )
			event = 1
		elseif t - self.t_enter > self.terminal_timeout then
			self.state = SEARCH -- lost: wait for the next swing
			self.t_enter = t
		end
	elseif s == STANCE then
		if t - self.hs_time > self.lockout_frac * self:mean_stride() then
			self.state = PRESWING
			self.t_enter = t
			self.ext_y = y
			self.ext_t = t
		end
	elseif s == PRESWING then
		if y < self.ext_y then
			self.ext_y = y
			self.ext_t = t
		end
		if self.ext_y < -self.to_depth_dps and y > self.ext_y + self.to_rise_dps then
			self.to_time = self.ext_t
			self.to_detect = t
			self.n_to = self.n_to + 1
			self.state = SEARCH
			self.t_enter = t
			event = 2
		elseif t - self.hs_time > 2.0 then
			self.state = SEARCH -- no toe-off within 2 s of heel strike
			self.t_enter = t
		end
	end
	self.t_prev = t
	self.y_prev = y
	return event
end

function Detector:phase( t )
	if self.n_hs == 0 then return -1.0 end
	local p = ( t - self.hs_time ) / self:mean_stride()
	if p > 1.0 then p = 1.0 end
	return p
end

return Detector
end

-- ScriptController that only measures: a simulated gyroscope on the right
-- shank (gyro.lua) and the gait-event detector running on it (detector.lua),
-- logged with store_data. Applies no force.
-- Properties (strings, from the ScriptController block):
--   body (default tibia_r), rate_hz (100), noise_dps (0.5), bias_dps (2),
--   imu_delay_s (0.015), seed (1), and the detector settings of detector.lua
--   (swing_dps, hs_feature, hs_depth_dps, hs_rise_dps, to_depth_dps,
--   to_rise_dps, lockout_frac, terminal_timeout, stride0).

local Gyro = require "gyro"
local Detector = require "detector"
local RAD2DEG = 180.0 / math.pi

function init( model, par, side )
	body = model:find_body( scone.body or "tibia_r" )
	gyro = Gyro.new(
		tonumber( scone.rate_hz ) or 100,
		tonumber( scone.noise_dps ) or 0.5,
		tonumber( scone.bias_dps ) or 2.0,
		tonumber( scone.imu_delay_s ) or 0.015,
		tonumber( scone.seed ) or 1 )
	detector = Detector.new( {
		swing_dps = tonumber( scone.swing_dps ),
		hs_feature = scone.hs_feature,
		hs_depth_dps = tonumber( scone.hs_depth_dps ),
		hs_rise_dps = tonumber( scone.hs_rise_dps ),
		to_depth_dps = tonumber( scone.to_depth_dps ),
		to_rise_dps = tonumber( scone.to_rise_dps ),
		lockout_frac = tonumber( scone.lockout_frac ),
		terminal_timeout = tonumber( scone.terminal_timeout ),
		stride0 = tonumber( scone.stride0 ) } )
	w_true = 0.0
	phase = -1.0
end

function update( model, t )
	w_true = body:ang_vel().z * RAD2DEG
	if gyro:update( t, w_true ) then
		detector:update( t, gyro.output )
	end
	phase = detector:phase( t )
	return false
end

function store_data( frame )
	frame:set_value( "imu.true", w_true )
	frame:set_value( "imu.measured", gyro.output )
	frame:set_value( "imu.output_k", gyro.output_k )
	frame:set_value( "imu.sample_true", gyro.sample_true )
	frame:set_value( "imu.sample_k", gyro.k )
	frame:set_value( "det.state", detector.state )
	frame:set_value( "det.n_hs", detector.n_hs )
	frame:set_value( "det.n_to", detector.n_to )
	frame:set_value( "det.hs_time", detector.hs_time )
	frame:set_value( "det.hs_detect", detector.hs_detect )
	frame:set_value( "det.to_time", detector.to_time )
	frame:set_value( "det.to_detect", detector.to_detect )
	frame:set_value( "det.phase", phase )
end
